const actionTypesResources = {
	LOAD_SUCCESS_RESOURCES: 'LOAD_SUCCESS_RESOURCES',
	LOAD_FAILURE_RESOURCES: 'LOAD_FAILURE_RESOURCES',
	LOADING_RESOURCES: 'LOADING_RESOURCES'
}

export default actionTypesResources
