const actionTypesCategories = {
	LOAD_SUCCESS_CATEGORIES: 'LOAD_SUCCESS_CATEGORIES',
	LOAD_FAILURE_CATEGORIES: 'LOAD_FAILURE_CATEGORIES',
	LOADING_CATEGORIES: 'LOADING_CATEGORIES'
}

export default actionTypesCategories
